### ISSUE TITLE
Could you pls share me with your JSONNet and model file? 

### ISSUE THREAD

**Issue by ha-lins** [isaacmg/ai-virus#2]
Hi, @isaacmg

I'm glad to see that you have investigated to implement a wrapper for meta-learning in [allennlp](https://github.com/allenai/allennlp/issues/3064#issuecomment-537637163), which is exactly what I need now. I saw the corresponding repo that you forked and committed ever. It seems that the metatrainer class needs to be fixed the param problem. Do you have the plan to finish it up? If so, I'm delighted to help you with it. 

Moreover, could you pls give me your e-mail for more convenient contact?

Thanks a lot!

**Comment by isaacmg** [comment]
Closing as this is related to another project. Please see my response on the AllenNLP issue.
